config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


  root "welcome#index"
  get '/register', to: 'users#new', as: 'register_user'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:show, :create] do
    resources :discover, only: [:index]
    resources :movies, controller: "user_movies", only: [:index, :show] do
      resources :viewing_party, controller: "user_parties", only: [:new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
   validates_presence_of :name, :email
   validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
   validates_presence_of :password
   has_secure_password

   has_many :user_parties
   has_many :viewing_parties, through: :user_parties

end

app/models/user_party.rb
class UserParty < ApplicationRecord
  validates_presence_of :user, :viewing_party
  
  belongs_to :viewing_party
  belongs_to :user
end

app/models/viewing_party.rb
class ViewingParty < ApplicationRecord
   has_many :user_parties
   has_many :users, through: :user_parties

   def find_host
      users.where("user_parties.host = true").first
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   private

   def error_message(errors)
      errors.full_messages.join(', ')
   end
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
    
    def index
        @user = User.find(params[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: email)
    
    if user.authenticate(password)
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.name}"
      session[:location] = params[:location]
      redirect_to user_path(user)
      # if user.admin?
      #   redirect_to admin_dashboard_path
    else
      flash[:error] = "Sorry, your credentials are bad."
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  private

  def email
    params[:email]
  end

  def password
    params[:password]
  end
end

app/controllers/user_movies_controller.rb
class UserMoviesController < ApplicationController
    
    def index
        
        @user = User.find(params[:user_id])
        @search = params[:search]
        
        if @search.present?
            @movies = MoviesFacade.new.search_movies(@search)
        elsif params[:q] = "top rated"
            @movies = MoviesFacade.new.top_rated_movies
        end
    end

    def show
        @user = User.find(params[:user_id])
        @movie = MoviesFacade.new.fetch_movie_by_id(params[:id])
    end
end

app/controllers/user_parties_controller.rb
class UserPartiesController < ApplicationController
    def new
        @movie = MoviesFacade.new.fetch_movie_by_id(params[:movie_id])
        @users = User.all
    end

    def create

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def new
      @user = User.new
   end

   def show
      @user = User.find(params[:id])
   end

   def create
      user = User.new(user_params)
      if user.save
         flash[:success] = 'Successfully Created New User'
         redirect_to user_path(user)
      else
         flash[:error] = "#{error_message(user.errors)}"
         redirect_to register_user_path
      end   
   end

private

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all

    # if session[:user_id].nil?
    #   flash[:notice] = "You must be logged in or registered to access a user's dashboard."
    #   redirect_to root_path
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def minutes_to_hours_minutes(minutes)
        hours = minutes / 60
        remaining_minutes = minutes % 60
        "#{hours} #{'hour' if hours == 1} #{'hours' unless hours == 1} #{remaining_minutes} minutes"

        
    end      
end

app/views/discover/index.html.erb
<center>
    <h1>Viewing Party</h1>
    <h6>Discover Movies</h6>
    <%=button_to "Find Top Rated Movies", user_movies_path(@user, q: "top rated"), method: :get %>
    <br>
    <%= form_with url: user_movies_path(@user), method: :get, local: true do |form| %>
        <%= form.label :search%>
        <%= form.text_field :search %>
        <%= form.submit 'Find Movies' %>
    <% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewingPartyLite7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/nav" %>

    <div id="mainBody" class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <%= yield %>  
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="nav-container container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="nav navbar-nav pull-right">
      <li><%= link_to 'Home', root_path, style: 'pull-right' %>
    </ul>
  </nav>
</div>

app/views/user_movies/index.html.erb
<center>
    <h1>Viewing Party</h1>
    <h6>Movie results for: <%=@search%></h6>
    <%=button_to "Discover Page", user_discover_index_path(@user) , method: :get%>
</center>    

<%@movies.each do |movie|%>
    <section class="movie">
   <p class="title vote_avg"><%=link_to "#{movie.title}", user_movie_path(@user, movie.id) %> Vote Average: <%=movie.vote_avg%></p>
   </section>
<%end%>

app/views/user_movies/show.html.erb
<center>
    <div class="headers">
        <h1>Viewing Party</h1>
        <h6><%=@movie.title%></h6>
    </div>
    <%=button_to "Discover Page", user_discover_index_path(@user) , method: :get%>
    <br>
    
    <%=button_to "Create Viewing Party for #{@movie.title}", 
                new_user_movie_viewing_party_path(@user, @movie.id), 
                method: :get%>
    <br>

    <div class="movie_specs">
        <p><strong>Vote: <%=@movie.vote_avg%>&nbsp;&nbsp;&nbsp;
        Runtime: <%=minutes_to_hours_minutes(@movie.runtime)%>&nbsp;&nbsp;&nbsp; 
        Genre: <%=@movie.genres.to_sentence%></strong></p>
    </div>
</center>
<div class="summary">
    <h4>Summary</h4>
    <p><%=@movie.summary%></p>
</div>

<div class="cast_members">
    <h4>Cast</h4>
    <%@movie.cast.each do |cast_member|%>
        <p class="member_name character"><%=cast_member.name%> as <%=cast_member.character%></p>
    <%end%>
</div>

<div class="reviews">
    <h4 class="review_count"><%=@movie.review_count%> Reviews:</h4>
    <%@movie.reviews.each do |review|%>
        <p class="review_author review_content"><%=review.author%>: <%=review.content%></p>
    <%end%>
</div> 

app/views/user_parties/new.html.erb
<p>HI</p>

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path, method: :post, data: {turbo: false}, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %><br>
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %><br>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %><br>


  <%= f.submit 'Create New User', class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1><%= "#{@user.name}'s Dashboard" %></h1><br>
<%if session[:location].present?%>
  <p>Your location: <%=session[:location]%></p>
<%end%>

<section class="viewing_parties">
  <% @user.viewing_parties.each do |party| %>
    <div class="viewing_party">
         Party Time: <%= party.date %> at <%= party.start_time %><br>
         Host: <%= party.find_host.name %><br>
         Who's Coming? <br/>

         <ol>
            <% party.users.each do |attendee| %>
               <li><%= attendee.name %> </li>
            <% end %>
         </ol>

    </div><br>
  <% end %>
</section>

<%= button_to 'Logout', logout_path, method: :delete%>

app/views/welcome/index.html.erb
<h1>Viewing Party</h1>

<%if session[:user_id].present?%>
   <h2>Existing Users</h2>
   <ul id="existing_users">
      <% @users.each do |user| %>
         <li><%= user.email%></li>
      <% end %>
   </ul>
   <%=button_to 'Logout', logout_path, method: :delete%>
<%else%>
   <%= link_to 'Log In', login_path %>
   <%= button_to 'Create New User', register_user_path, method: :get, class: "btn btn-lg btn-outline-secondary" %><br>
<%end%>